apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    osinstance/service: backendmanage
    osinstance/name: {{ .URL }}
  name: backendmanage
  namespace: {{ .StackName }}
spec:
  ports:
    - name: "9002"
      port: 9002
      targetPort: 9002
  selector:
    osinstance/service: backendmanage
status:
  loadBalancer: {}
