apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    osinstance/service: datastorewriter
    osinstance/name: {{ .URL }}
  name: datastorewriter
  namespace: {{ .StackName }}
{{- with .Services.datastoreWriter }}
spec:
  replicas: {{ or .CustomKeys.replicas 1 }}
  selector:
    matchLabels:
      osinstance/service: datastorewriter
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        osinstance/name: {{ $.URL }}
        osinstance/service: datastorewriter
    spec:
      containers:
        - name: datastorewriter
          image: {{ .ContainerRegistry }}/openslides-datastore-writer:{{ .Tag }}
          imagePullPolicy: Always
          ports:
            - containerPort: 9011
          startupProbe:
            httpGet:
              path: /internal/datastore/writer/health
              port: 9011
            periodSeconds: 1
            failureThreshold: 60
          readinessProbe:
            httpGet:
              path: /internal/datastore/writer/health
              port: 9011
            periodSeconds: 30
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /internal/datastore/writer/health
              port: 9011
            periodSeconds: 30
            failureThreshold: 3
          env:
            {{- with .Environment }}{{ envMapToK8S . | marshalContent 12 }}{{- end }}
          envFrom:
            - configMapRef:
                name: default-environment
          resources: {}
          volumeMounts:
            - mountPath: /run/secrets/postgres-password
              name: postgres-password
      restartPolicy: Always
      volumes:
        - name: postgres-password
          secret:
            items:
              - key: postgres-password
                path: postgres-password
            secretName: postgres-password
status: {}
{{- end }}
