apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    osinstance/service: manage
    osinstance/name: {{ .URL }}
  name: manage
  namespace: {{ .StackName }}
spec:
  ports:
    - name: "9008"
      port: 9008
      targetPort: 9008
  selector:
    osinstance/service: manage
status:
  loadBalancer: {}
