{{- if checkFlag .DisablePostgres }}{{ else }}
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    osinstance/service: postgres
    osinstance/name: {{ .URL }}
  name: postgres
  namespace: {{ .StackName }}
{{- with .Services.postgres }}
spec:
  replicas: {{ or .CustomKeys.replicas 1 }}
  selector:
    matchLabels:
      osinstance/service: postgres
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        osinstance/name: {{ $.URL }}
        osinstance/service: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:13
          imagePullPolicy: Always
          ports:
            - containerPort: 5432
          env:
            {{- with .Environment }}{{ envMapToK8S . | marshalContent 12 }}{{- end }}
          envFrom:
            - configMapRef:
                name: default-environment
          resources: {}
          volumeMounts:
            - mountPath: /run/secrets/postgres-password
              name: postgres-password
      restartPolicy: Always
      volumes:
        - name: postgres-password
          secret:
            items:
              - key: postgres-password
                path: postgres-password
            secretName: postgres-password
status: {}
{{- end }}
{{- end }}
