apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    osinstance/service: redis
    osinstance/name: {{ .URL }}
  name: redis
  namespace: {{ .StackName }}
spec:
  ports:
    - name: "6379"
      port: 6379
      targetPort: 6379
  selector:
    osinstance/service: redis
status:
  loadBalancer: {}
